<?php

return [
    'default' => [
        'name' => 'Legacy BBS',
        'background' => '#004040',
        'text' => '#ffffff',
        'link' => '#efefee',
        'link_visited' => '#dddddd',
        'link_hover' => '#10e0e0',
        'link_active' => '#ff0000',
        'hr' => '#c0c0c0',
        'title' => '#fffffe',
        'quote' => '#cccccc',
        'error' => '#ff0000',
        'input_bg' => '#ffffff',
        'input_text' => '#000000',
        'input_border' => '#999999',
        'input_hover' => '#eeeeff',
        'input_focus' => '#dddddd',
        'button_bg' => '#ffffff',
        'button_text' => '#000000',
        'button_hover' => '#ccddff',
        'button_active' => '#88bbff',
    ],

    'dark' => [
        'name' => 'Dark',
        'background' => '#1a1a1a',
        'text' => '#e0e0e0',
        'link' => '#88ccff',
        'link_visited' => '#bb99ff',
        'link_hover' => '#aaddff',
        'link_active' => '#ff6666',
        'hr' => '#444444',
        'title' => '#ffffff',
        'quote' => '#999999',
        'error' => '#ff4444',
        'input_bg' => '#2a2a2a',
        'input_text' => '#e0e0e0',
        'input_border' => '#555555',
        'input_hover' => '#333333',
        'input_focus' => '#3a3a3a',
        'button_bg' => '#3a3a3a',
        'button_text' => '#e0e0e0',
        'button_hover' => '#4a4a4a',
        'button_active' => '#5a5a5a',
    ],

    'custom' => [
        'name' => 'Custom',
        'background' => '#004040',
        'text' => '#ffffff',
        'link' => '#efefee',
        'link_visited' => '#dddddd',
        'link_hover' => '#10e0e0',
        'link_active' => '#ff0000',
        'hr' => '#c0c0c0',
        'title' => '#fffffe',
        'quote' => '#cccccc',
        'error' => '#ff0000',
        'input_bg' => '#ffffff',
        'input_text' => '#000000',
        'input_border' => '#999999',
        'input_hover' => '#eeeeff',
        'input_focus' => '#dddddd',
        'button_bg' => '#ffffff',
        'button_text' => '#000000',
        'button_hover' => '#ccddff',
        'button_active' => '#88bbff',
    ],
];
